CREATE TABLE translations
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    translation_key   VARCHAR(255),
    translation_value VARCHAR(255),
    language          VARCHAR(255),
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_translations PRIMARY KEY (id)
);